const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 79,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 79,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 79,
      brand: 'Perry',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular shirt',
    },
    {
      name: 'Emo Pants',
      slug: 'emo-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 79,
      brand: 'Hammerhead',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular pants',
    },
    {
      name: 'Jogger',
      slug: 'jogger',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 79,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A Popular shirt',
    },
  ],
}

export default data
